export const TRANSACTION_CATEGORIES = [
  "Food & Dining",
  "Transportation",
  "Shopping",
  "Bills & Utilities",
  "Entertainment",
  "Health & Fitness",
  "Travel",
  "Education",
  "Gifts & Donations",
  "Other",
];

export const PAYMENT_CATEGORIES = [
  "Bills",
  "Subscriptions",
  "Loans",
  "Insurance",
  "Memberships",
  "Rent",
  "Utilities",
  "Other",
];

export const TAGS = [
  "Monthly",
  "Quarterly",
  "Annual",
  "Essential",
  "Optional",
  "Auto-pay",
  "Manual",
  "Recurring",
  "One-time",
  "Groceries",
  "Restaurants",
  "Gas",
  "Public Transport",
  "Clothing",
  "Electronics",
  "Home Goods",
  "Utilities",
  "Rent",
  "Insurance",
  "Movies",
  "Sports",
  "Gym",
  "Medical",
  "Flights",
  "Hotels",
  "Books",
  "Courses",
  "Charity",
  "Personal Care",
];
